services:
  coordinator:
    image: mapreduce-coordinator:latest
    container_name: coor
    hostname: coordinator
    environment:
      - NUM_WORKERS=8
      - DATASET_URL=https://mattmahoney.net/dc/enwik9.zip
      - MAP_CHUNKS_PER_WORKER=8
      - PYTHONUNBUFFERED=1
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net
    depends_on:
      - worker-1
      - worker-2
      - worker-3
      - worker-4
      - worker-5
      - worker-6
      - worker-7
      - worker-8

  worker-1:
    image: mapreduce-worker:latest
    container_name: worker-1
    hostname: worker-1
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-2:
    image: mapreduce-worker:latest
    container_name: worker-2
    hostname: worker-2
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-3:
    image: mapreduce-worker:latest
    container_name: worker-3
    hostname: worker-3
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-4:
    image: mapreduce-worker:latest
    container_name: worker-4
    hostname: worker-4
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-5:
    image: mapreduce-worker:latest
    container_name: worker-5
    hostname: worker-5
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-6:
    image: mapreduce-worker:latest
    container_name: worker-6
    hostname: worker-6
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-7:
    image: mapreduce-worker:latest
    container_name: worker-7
    hostname: worker-7
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

  worker-8:
    image: mapreduce-worker:latest
    container_name: worker-8
    hostname: worker-8
    volumes:
      - ./txt:/app/txt
      - ./intermediate:/app/intermediate
      - ./output:/app/output
    networks:
      - mapreduce-net

networks:
  mapreduce-net:
    driver: bridge